image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Environment
    init: |
      # تحديث متغيرات البيئة
      echo "export ANDROID_SDK_ROOT=\"/home/gitpod/android-sdk\"" >> ~/.bashrc
      echo "export PATH=\"\$PATH:\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin\"" >> ~/.bashrc
      source ~/.bashrc
      
      # تثبيت تبعيات المشروع
      flutter pub get
      
      # إنشاء ملف local.properties
      echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      
      # قبول تراخيص Android نهائياً
      yes | flutter doctor --android-licenses

    command: flutter build apk --release

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
    - nash.awesome-flutter-snippets
